# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conjunction_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_conjunctionwidget(object):
    def setupUi(self, conjunctionwidget):
        conjunctionwidget.setObjectName("conjunctionwidget")
        conjunctionwidget.resize(450, 700)
        conjunctionwidget.setMinimumSize(QtCore.QSize(450, 500))
        conjunctionwidget.setMaximumSize(QtCore.QSize(600, 1000))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(conjunctionwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(conjunctionwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ut_groupbox = QtWidgets.QGroupBox(conjunctionwidget)
        self.ut_groupbox.setEnabled(True)
        self.ut_groupbox.setFlat(False)
        self.ut_groupbox.setCheckable(True)
        self.ut_groupbox.setChecked(True)
        self.ut_groupbox.setObjectName("ut_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ut_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radec_container = QtWidgets.QWidget(self.ut_groupbox)
        self.radec_container.setEnabled(False)
        self.radec_container.setObjectName("radec_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.radec_container)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.radec_container)
        self.dt_groupbox = QtWidgets.QGroupBox(self.ut_groupbox)
        self.dt_groupbox.setFlat(True)
        self.dt_groupbox.setCheckable(True)
        self.dt_groupbox.setChecked(False)
        self.dt_groupbox.setObjectName("dt_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dt_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.dt_groupbox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.dt_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 1, 1, 1)
        self.ra_m_spinbox = QtWidgets.QSpinBox(self.dt_groupbox)
        self.ra_m_spinbox.setMaximum(59)
        self.ra_m_spinbox.setObjectName("ra_m_spinbox")
        self.gridLayout_3.addWidget(self.ra_m_spinbox, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.dt_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 3, 1, 1)
        self.dec_d_spinbox = QtWidgets.QSpinBox(self.dt_groupbox)
        self.dec_d_spinbox.setMinimum(-90)
        self.dec_d_spinbox.setMaximum(90)
        self.dec_d_spinbox.setObjectName("dec_d_spinbox")
        self.gridLayout_3.addWidget(self.dec_d_spinbox, 3, 1, 1, 1)
        self.ra_s_spinbox = QtWidgets.QSpinBox(self.dt_groupbox)
        self.ra_s_spinbox.setMaximum(59)
        self.ra_s_spinbox.setObjectName("ra_s_spinbox")
        self.gridLayout_3.addWidget(self.ra_s_spinbox, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.dt_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.dt_groupbox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.dec_m_spinbox = QtWidgets.QSpinBox(self.dt_groupbox)
        self.dec_m_spinbox.setMaximum(59)
        self.dec_m_spinbox.setObjectName("dec_m_spinbox")
        self.gridLayout_3.addWidget(self.dec_m_spinbox, 3, 2, 1, 1)
        self.ra_h_spinbox = QtWidgets.QSpinBox(self.dt_groupbox)
        self.ra_h_spinbox.setMaximum(23)
        self.ra_h_spinbox.setObjectName("ra_h_spinbox")
        self.gridLayout_3.addWidget(self.ra_h_spinbox, 1, 1, 1, 1)
        self.dec_s_spinbox = QtWidgets.QSpinBox(self.dt_groupbox)
        self.dec_s_spinbox.setMaximum(59)
        self.dec_s_spinbox.setObjectName("dec_s_spinbox")
        self.gridLayout_3.addWidget(self.dec_s_spinbox, 3, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.dt_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.dt_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.dt_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.dt_groupbox)
        self.gridLayout.addWidget(self.ut_groupbox, 2, 0, 1, 4)
        self.line_2 = QtWidgets.QFrame(conjunctionwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 4)
        self.export_btn = QtWidgets.QPushButton(conjunctionwidget)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout.addWidget(self.export_btn, 0, 2, 1, 1)
        self.compute_btn = QtWidgets.QPushButton(conjunctionwidget)
        self.compute_btn.setObjectName("compute_btn")
        self.gridLayout.addWidget(self.compute_btn, 0, 3, 1, 1)
        self.data_treewidget = QtWidgets.QTreeWidget(conjunctionwidget)
        self.data_treewidget.setObjectName("data_treewidget")
        self.gridLayout.addWidget(self.data_treewidget, 4, 0, 1, 4)
        self.line = QtWidgets.QFrame(conjunctionwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.kstep_spinbox = QtWidgets.QSpinBox(conjunctionwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kstep_spinbox.sizePolicy().hasHeightForWidth())
        self.kstep_spinbox.setSizePolicy(sizePolicy)
        self.kstep_spinbox.setMinimum(1)
        self.kstep_spinbox.setMaximum(99999)
        self.kstep_spinbox.setObjectName("kstep_spinbox")
        self.gridLayout.addWidget(self.kstep_spinbox, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(conjunctionwidget)
        QtCore.QMetaObject.connectSlotsByName(conjunctionwidget)
        conjunctionwidget.setTabOrder(self.ra_h_spinbox, self.ra_m_spinbox)
        conjunctionwidget.setTabOrder(self.ra_m_spinbox, self.ra_s_spinbox)
        conjunctionwidget.setTabOrder(self.ra_s_spinbox, self.dec_d_spinbox)
        conjunctionwidget.setTabOrder(self.dec_d_spinbox, self.dec_m_spinbox)
        conjunctionwidget.setTabOrder(self.dec_m_spinbox, self.dec_s_spinbox)
        conjunctionwidget.setTabOrder(self.dec_s_spinbox, self.ut_groupbox)
        conjunctionwidget.setTabOrder(self.ut_groupbox, self.dt_groupbox)
        conjunctionwidget.setTabOrder(self.dt_groupbox, self.export_btn)
        conjunctionwidget.setTabOrder(self.export_btn, self.compute_btn)
        conjunctionwidget.setTabOrder(self.compute_btn, self.data_treewidget)
        conjunctionwidget.setTabOrder(self.data_treewidget, self.kstep_spinbox)

    def retranslateUi(self, conjunctionwidget):
        _translate = QtCore.QCoreApplication.translate
        conjunctionwidget.setWindowTitle(_translate("conjunctionwidget", "Compute Conjunction Times"))
        self.label.setToolTip(_translate("conjunctionwidget", "Space conjunction times by a whole orbit cycles per minima [KTSTEP]"))
        self.label.setText(_translate("conjunctionwidget", "Cycle Step"))
        self.ut_groupbox.setTitle(_translate("conjunctionwidget", "Compute &UTC"))
        self.dt_groupbox.setTitle(_translate("conjunctionwidget", "Convert HJD &to JD"))
        self.label_16.setText(_translate("conjunctionwidget", "Right Ascension"))
        self.label_11.setText(_translate("conjunctionwidget", "°"))
        self.label_15.setText(_translate("conjunctionwidget", "\""))
        self.label_10.setText(_translate("conjunctionwidget", "Second"))
        self.label_17.setText(_translate("conjunctionwidget", "Declination"))
        self.label_13.setText(_translate("conjunctionwidget", "\'"))
        self.label_14.setText(_translate("conjunctionwidget", "Minute"))
        self.label_12.setText(_translate("conjunctionwidget", "Hour"))
        self.export_btn.setText(_translate("conjunctionwidget", "Export"))
        self.compute_btn.setText(_translate("conjunctionwidget", "Compute"))
        self.data_treewidget.headerItem().setText(0, _translate("conjunctionwidget", "HJD"))
        self.data_treewidget.headerItem().setText(1, _translate("conjunctionwidget", "Min"))
        self.data_treewidget.headerItem().setText(2, _translate("conjunctionwidget", "D/M/Y - H:M:S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    conjunctionwidget = QtWidgets.QWidget()
    ui = Ui_conjunctionwidget()
    ui.setupUi(conjunctionwidget)
    conjunctionwidget.show()
    sys.exit(app.exec_())

