# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dc_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DCWidget(object):
    def setupUi(self, DCWidget):
        DCWidget.setObjectName("DCWidget")
        DCWidget.resize(1355, 700)
        DCWidget.setMinimumSize(QtCore.QSize(1355, 615))
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(DCWidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.exportresults_btn = QtWidgets.QPushButton(DCWidget)
        self.exportresults_btn.setEnabled(True)
        self.exportresults_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.exportresults_btn.setObjectName("exportresults_btn")
        self.gridLayout.addWidget(self.exportresults_btn, 1, 4, 1, 1)
        self.viewlastdcin_btn = QtWidgets.QPushButton(DCWidget)
        self.viewlastdcin_btn.setMaximumSize(QtCore.QSize(125, 16777215))
        self.viewlastdcin_btn.setObjectName("viewlastdcin_btn")
        self.gridLayout.addWidget(self.viewlastdcin_btn, 0, 6, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DCWidget)
        self.label.setMinimumSize(QtCore.QSize(145, 0))
        self.label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.iteration_spinbox = QtWidgets.QSpinBox(DCWidget)
        self.iteration_spinbox.setMinimumSize(QtCore.QSize(50, 0))
        self.iteration_spinbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.iteration_spinbox.setMinimum(1)
        self.iteration_spinbox.setObjectName("iteration_spinbox")
        self.horizontalLayout.addWidget(self.iteration_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(DCWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 5, 2, 1)
        self.line1 = QtWidgets.QFrame(DCWidget)
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.gridLayout.addWidget(self.line1, 0, 3, 2, 1)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.label_8 = QtWidgets.QLabel(DCWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(145, 0))
        self.label_8.setMaximumSize(QtCore.QSize(145, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout1.addWidget(self.label_8)
        self.niter_spinbox = QtWidgets.QSpinBox(DCWidget)
        self.niter_spinbox.setMinimumSize(QtCore.QSize(50, 0))
        self.niter_spinbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.niter_spinbox.setMinimum(1)
        self.niter_spinbox.setObjectName("niter_spinbox")
        self.horizontalLayout1.addWidget(self.niter_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout1, 1, 0, 1, 1)
        self.updateinputs_btn = QtWidgets.QPushButton(DCWidget)
        self.updateinputs_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.updateinputs_btn.setObjectName("updateinputs_btn")
        self.gridLayout.addWidget(self.updateinputs_btn, 0, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(DCWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 1, 2, 1)
        self.viewlaastdcout_btn = QtWidgets.QPushButton(DCWidget)
        self.viewlaastdcout_btn.setMaximumSize(QtCore.QSize(125, 16777215))
        self.viewlaastdcout_btn.setObjectName("viewlaastdcout_btn")
        self.gridLayout.addWidget(self.viewlaastdcout_btn, 1, 6, 1, 1)
        self.removesubset_btn = QtWidgets.QPushButton(DCWidget)
        self.removesubset_btn.setEnabled(False)
        self.removesubset_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.removesubset_btn.setObjectName("removesubset_btn")
        self.gridLayout.addWidget(self.removesubset_btn, 1, 8, 1, 1)
        self.addsubset_btn = QtWidgets.QPushButton(DCWidget)
        self.addsubset_btn.setEnabled(False)
        self.addsubset_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.addsubset_btn.setObjectName("addsubset_btn")
        self.gridLayout.addWidget(self.addsubset_btn, 0, 8, 1, 1)
        self.rundc2015_btn = QtWidgets.QPushButton(DCWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rundc2015_btn.sizePolicy().hasHeightForWidth())
        self.rundc2015_btn.setSizePolicy(sizePolicy)
        self.rundc2015_btn.setMaximumSize(QtCore.QSize(900, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rundc2015_btn.setFont(font)
        self.rundc2015_btn.setObjectName("rundc2015_btn")
        self.gridLayout.addWidget(self.rundc2015_btn, 0, 2, 2, 1)
        self.line_19 = QtWidgets.QFrame(DCWidget)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout.addWidget(self.line_19, 0, 7, 2, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.line_9 = QtWidgets.QFrame(DCWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_9.addWidget(self.line_9)
        self.tab_widget = QtWidgets.QTabWidget(DCWidget)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.keepdel_tab_widget = QtWidgets.QTabWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepdel_tab_widget.sizePolicy().hasHeightForWidth())
        self.keepdel_tab_widget.setSizePolicy(sizePolicy)
        self.keepdel_tab_widget.setMaximumSize(QtCore.QSize(825, 16777215))
        self.keepdel_tab_widget.setTabPosition(QtWidgets.QTabWidget.West)
        self.keepdel_tab_widget.setObjectName("keepdel_tab_widget")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_7.setSpacing(3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.logd_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logd_chk.setFont(font)
        self.logd_chk.setObjectName("logd_chk")
        self.gridLayout_7.addWidget(self.logd_chk, 3, 4, 1, 1)
        self.s2long_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2long_chk.setFont(font)
        self.s2long_chk.setObjectName("s2long_chk")
        self.gridLayout_7.addWidget(self.s2long_chk, 8, 1, 1, 1)
        self.t2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t2_chk.setFont(font)
        self.t2_chk.setObjectName("t2_chk")
        self.gridLayout_7.addWidget(self.t2_chk, 4, 1, 1, 1)
        self.f2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f2_chk.setFont(font)
        self.f2_chk.setObjectName("f2_chk")
        self.gridLayout_7.addWidget(self.f2_chk, 5, 1, 1, 1)
        self.el3_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.el3_chk.setFont(font)
        self.el3_chk.setToolTip("")
        self.el3_chk.setObjectName("el3_chk")
        self.gridLayout_7.addWidget(self.el3_chk, 6, 6, 1, 1)
        self.s1tmax1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1tmax1_chk.setFont(font)
        self.s1tmax1_chk.setObjectName("s1tmax1_chk")
        self.gridLayout_7.addWidget(self.s1tmax1_chk, 7, 5, 1, 1)
        self.s1lat_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1lat_chk.setFont(font)
        self.s1lat_chk.setObjectName("s1lat_chk")
        self.gridLayout_7.addWidget(self.s1lat_chk, 7, 0, 1, 1)
        self.s2temp_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2temp_chk.setFont(font)
        self.s2temp_chk.setObjectName("s2temp_chk")
        self.gridLayout_7.addWidget(self.s2temp_chk, 8, 3, 1, 1)
        self.g2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.g2_chk.setFont(font)
        self.g2_chk.setObjectName("g2_chk")
        self.gridLayout_7.addWidget(self.g2_chk, 4, 3, 1, 1)
        self.p0_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p0_chk.setFont(font)
        self.p0_chk.setObjectName("p0_chk")
        self.gridLayout_7.addWidget(self.p0_chk, 2, 1, 1, 1)
        self.s1tstart_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1tstart_chk.setFont(font)
        self.s1tstart_chk.setObjectName("s1tstart_chk")
        self.gridLayout_7.addWidget(self.s1tstart_chk, 7, 4, 1, 1)
        self.pot1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pot1_chk.setFont(font)
        self.pot1_chk.setObjectName("pot1_chk")
        self.gridLayout_7.addWidget(self.pot1_chk, 5, 6, 1, 1)
        self.s1rad_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1rad_chk.setFont(font)
        self.s1rad_chk.setObjectName("s1rad_chk")
        self.gridLayout_7.addWidget(self.s1rad_chk, 7, 2, 1, 1)
        self.x1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x1_chk.setFont(font)
        self.x1_chk.setObjectName("x1_chk")
        self.gridLayout_7.addWidget(self.x1_chk, 5, 4, 1, 1)
        self.p3b_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p3b_chk.setFont(font)
        self.p3b_chk.setObjectName("p3b_chk")
        self.gridLayout_7.addWidget(self.p3b_chk, 6, 1, 1, 1)
        self.s2tmax1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2tmax1_chk.setFont(font)
        self.s2tmax1_chk.setObjectName("s2tmax1_chk")
        self.gridLayout_7.addWidget(self.s2tmax1_chk, 8, 5, 1, 1)
        self.dpdt_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dpdt_chk.setFont(font)
        self.dpdt_chk.setObjectName("dpdt_chk")
        self.gridLayout_7.addWidget(self.dpdt_chk, 2, 2, 1, 1)
        self.t1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t1_chk.setFont(font)
        self.t1_chk.setObjectName("t1_chk")
        self.gridLayout_7.addWidget(self.t1_chk, 4, 0, 1, 1)
        self.q_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.q_chk.setFont(font)
        self.q_chk.setObjectName("q_chk")
        self.gridLayout_7.addWidget(self.q_chk, 3, 3, 1, 1)
        self.jd0_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.jd0_chk.setFont(font)
        self.jd0_chk.setObjectName("jd0_chk")
        self.gridLayout_7.addWidget(self.jd0_chk, 2, 0, 1, 1)
        self.s2tstart_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2tstart_chk.setFont(font)
        self.s2tstart_chk.setObjectName("s2tstart_chk")
        self.gridLayout_7.addWidget(self.s2tstart_chk, 8, 4, 1, 1)
        self.l1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l1_chk.setFont(font)
        self.l1_chk.setObjectName("l1_chk")
        self.gridLayout_7.addWidget(self.l1_chk, 5, 2, 1, 1)
        self.perr0_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perr0_chk.setFont(font)
        self.perr0_chk.setObjectName("perr0_chk")
        self.gridLayout_7.addWidget(self.perr0_chk, 2, 3, 1, 1)
        self.incl_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.incl_chk.setFont(font)
        self.incl_chk.setObjectName("incl_chk")
        self.gridLayout_7.addWidget(self.incl_chk, 3, 2, 1, 1)
        self.s1long_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1long_chk.setFont(font)
        self.s1long_chk.setObjectName("s1long_chk")
        self.gridLayout_7.addWidget(self.s1long_chk, 7, 1, 1, 1)
        self.f1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f1_chk.setFont(font)
        self.f1_chk.setObjectName("f1_chk")
        self.gridLayout_7.addWidget(self.f1_chk, 5, 0, 1, 1)
        self.s2tmax2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2tmax2_chk.setFont(font)
        self.s2tmax2_chk.setObjectName("s2tmax2_chk")
        self.gridLayout_7.addWidget(self.s2tmax2_chk, 8, 6, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab_11)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 1, 0, 1, 10)
        self.s1tmax2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1tmax2_chk.setFont(font)
        self.s1tmax2_chk.setObjectName("s1tmax2_chk")
        self.gridLayout_7.addWidget(self.s1tmax2_chk, 7, 6, 1, 1)
        self.l2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l2_chk.setFont(font)
        self.l2_chk.setObjectName("l2_chk")
        self.gridLayout_7.addWidget(self.l2_chk, 5, 3, 1, 1)
        self.e3b_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.e3b_chk.setFont(font)
        self.e3b_chk.setObjectName("e3b_chk")
        self.gridLayout_7.addWidget(self.e3b_chk, 6, 3, 1, 1)
        self.alb1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alb1_chk.setFont(font)
        self.alb1_chk.setObjectName("alb1_chk")
        self.gridLayout_7.addWidget(self.alb1_chk, 4, 4, 1, 1)
        self.xinc3b_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.xinc3b_chk.setFont(font)
        self.xinc3b_chk.setObjectName("xinc3b_chk")
        self.gridLayout_7.addWidget(self.xinc3b_chk, 6, 2, 1, 1)
        self.pshift_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pshift_chk.setFont(font)
        self.pshift_chk.setObjectName("pshift_chk")
        self.gridLayout_7.addWidget(self.pshift_chk, 2, 5, 1, 1)
        self.x2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x2_chk.setFont(font)
        self.x2_chk.setObjectName("x2_chk")
        self.gridLayout_7.addWidget(self.x2_chk, 5, 5, 1, 1)
        self.desextinc_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.desextinc_chk.setFont(font)
        self.desextinc_chk.setObjectName("desextinc_chk")
        self.gridLayout_7.addWidget(self.desextinc_chk, 6, 7, 1, 1)
        self.a3b_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.a3b_chk.setFont(font)
        self.a3b_chk.setObjectName("a3b_chk")
        self.gridLayout_7.addWidget(self.a3b_chk, 6, 0, 1, 1)
        self.tc3b_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tc3b_chk.setFont(font)
        self.tc3b_chk.setObjectName("tc3b_chk")
        self.gridLayout_7.addWidget(self.tc3b_chk, 6, 4, 1, 1)
        self.perr3b_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perr3b_chk.setFont(font)
        self.perr3b_chk.setObjectName("perr3b_chk")
        self.gridLayout_7.addWidget(self.perr3b_chk, 6, 5, 1, 1)
        self.vgam_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vgam_chk.setFont(font)
        self.vgam_chk.setObjectName("vgam_chk")
        self.gridLayout_7.addWidget(self.vgam_chk, 3, 5, 1, 1)
        self.s2rad_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2rad_chk.setFont(font)
        self.s2rad_chk.setObjectName("s2rad_chk")
        self.gridLayout_7.addWidget(self.s2rad_chk, 8, 2, 1, 1)
        self.s1tend_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1tend_chk.setFont(font)
        self.s1tend_chk.setObjectName("s1tend_chk")
        self.gridLayout_7.addWidget(self.s1tend_chk, 7, 7, 1, 1)
        self.g1_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.g1_chk.setFont(font)
        self.g1_chk.setObjectName("g1_chk")
        self.gridLayout_7.addWidget(self.g1_chk, 4, 2, 1, 1)
        self.dperdt_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dperdt_chk.setFont(font)
        self.dperdt_chk.setObjectName("dperdt_chk")
        self.gridLayout_7.addWidget(self.dperdt_chk, 2, 4, 1, 1)
        self.s2tend_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2tend_chk.setFont(font)
        self.s2tend_chk.setObjectName("s2tend_chk")
        self.gridLayout_7.addWidget(self.s2tend_chk, 8, 7, 1, 1)
        self.pot2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pot2_chk.setFont(font)
        self.pot2_chk.setObjectName("pot2_chk")
        self.gridLayout_7.addWidget(self.pot2_chk, 5, 7, 1, 1)
        self.alb2_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alb2_chk.setFont(font)
        self.alb2_chk.setObjectName("alb2_chk")
        self.gridLayout_7.addWidget(self.alb2_chk, 4, 5, 1, 1)
        self.e_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.e_chk.setFont(font)
        self.e_chk.setObjectName("e_chk")
        self.gridLayout_7.addWidget(self.e_chk, 3, 1, 1, 1)
        self.s1temp_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s1temp_chk.setFont(font)
        self.s1temp_chk.setObjectName("s1temp_chk")
        self.gridLayout_7.addWidget(self.s1temp_chk, 7, 3, 1, 1)
        self.s2lat_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s2lat_chk.setFont(font)
        self.s2lat_chk.setObjectName("s2lat_chk")
        self.gridLayout_7.addWidget(self.s2lat_chk, 8, 0, 1, 1)
        self.a_chk = QtWidgets.QCheckBox(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.a_chk.setFont(font)
        self.a_chk.setObjectName("a_chk")
        self.gridLayout_7.addWidget(self.a_chk, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_11)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 10)
        self.vlr_ipt = QtWidgets.QDoubleSpinBox(self.tab_11)
        self.vlr_ipt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.vlr_ipt.setDecimals(3)
        self.vlr_ipt.setMaximum(1.0)
        self.vlr_ipt.setSingleStep(0.01)
        self.vlr_ipt.setProperty("value", 1.0)
        self.vlr_ipt.setObjectName("vlr_ipt")
        self.gridLayout_7.addWidget(self.vlr_ipt, 3, 9, 1, 1)
        self.marqmul_ipt = QtWidgets.QDoubleSpinBox(self.tab_11)
        self.marqmul_ipt.setMaximumSize(QtCore.QSize(100, 25))
        self.marqmul_ipt.setDecimals(7)
        self.marqmul_ipt.setSingleStep(1e-05)
        self.marqmul_ipt.setProperty("value", 1e-05)
        self.marqmul_ipt.setObjectName("marqmul_ipt")
        self.gridLayout_7.addWidget(self.marqmul_ipt, 2, 9, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.tab_11)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_7.addWidget(self.line_6, 5, 8, 4, 1)
        self.clearbaseset_btn = QtWidgets.QPushButton(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearbaseset_btn.sizePolicy().hasHeightForWidth())
        self.clearbaseset_btn.setSizePolicy(sizePolicy)
        self.clearbaseset_btn.setObjectName("clearbaseset_btn")
        self.gridLayout_7.addWidget(self.clearbaseset_btn, 5, 9, 4, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 2, 6, 1, 3)
        self.label_81 = QtWidgets.QLabel(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout_7.addWidget(self.label_81, 3, 6, 1, 3)
        self.line_13 = QtWidgets.QFrame(self.tab_11)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_7.addWidget(self.line_13, 4, 6, 1, 4)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        self.keepdel_tab_widget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_12)
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_8.setSpacing(3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.del_s2agrad_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_s2agrad_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_s2agrad_ipt.setDecimals(4)
        self.del_s2agrad_ipt.setMinimum(0.0001)
        self.del_s2agrad_ipt.setSingleStep(0.001)
        self.del_s2agrad_ipt.setObjectName("del_s2agrad_ipt")
        self.gridLayout_8.addWidget(self.del_s2agrad_ipt, 7, 6, 1, 1)
        self.del_f2_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_f2_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_f2_ipt.setDecimals(4)
        self.del_f2_ipt.setMinimum(0.0001)
        self.del_f2_ipt.setSingleStep(0.001)
        self.del_f2_ipt.setProperty("value", 0.01)
        self.del_f2_ipt.setObjectName("del_f2_ipt")
        self.gridLayout_8.addWidget(self.del_f2_ipt, 5, 7, 1, 1)
        self.del_alb1_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_alb1_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_alb1_ipt.setDecimals(4)
        self.del_alb1_ipt.setMinimum(0.0001)
        self.del_alb1_ipt.setSingleStep(0.001)
        self.del_alb1_ipt.setProperty("value", 0.05)
        self.del_alb1_ipt.setObjectName("del_alb1_ipt")
        self.gridLayout_8.addWidget(self.del_alb1_ipt, 5, 4, 1, 1)
        self.del_g2_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_g2_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_g2_ipt.setDecimals(4)
        self.del_g2_ipt.setMinimum(0.0001)
        self.del_g2_ipt.setSingleStep(0.001)
        self.del_g2_ipt.setProperty("value", 0.01)
        self.del_g2_ipt.setObjectName("del_g2_ipt")
        self.gridLayout_8.addWidget(self.del_g2_ipt, 5, 1, 1, 1)
        self.del_g1_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_g1_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_g1_ipt.setDecimals(4)
        self.del_g1_ipt.setMinimum(0.0001)
        self.del_g1_ipt.setSingleStep(0.001)
        self.del_g1_ipt.setProperty("value", 0.01)
        self.del_g1_ipt.setObjectName("del_g1_ipt")
        self.gridLayout_8.addWidget(self.del_g1_ipt, 5, 0, 1, 1)
        self.del_x1_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_x1_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_x1_ipt.setDecimals(4)
        self.del_x1_ipt.setMinimum(0.0001)
        self.del_x1_ipt.setSingleStep(0.001)
        self.del_x1_ipt.setProperty("value", 0.01)
        self.del_x1_ipt.setObjectName("del_x1_ipt")
        self.gridLayout_8.addWidget(self.del_x1_ipt, 5, 8, 1, 1)
        self.del_s2tmpf_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_s2tmpf_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_s2tmpf_ipt.setDecimals(4)
        self.del_s2tmpf_ipt.setMinimum(0.0001)
        self.del_s2tmpf_ipt.setSingleStep(0.001)
        self.del_s2tmpf_ipt.setProperty("value", 0.02)
        self.del_s2tmpf_ipt.setObjectName("del_s2tmpf_ipt")
        self.gridLayout_8.addWidget(self.del_s2tmpf_ipt, 7, 7, 1, 1)
        self.del_t1_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_t1_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_t1_ipt.setDecimals(4)
        self.del_t1_ipt.setMinimum(0.0001)
        self.del_t1_ipt.setSingleStep(0.001)
        self.del_t1_ipt.setProperty("value", 0.02)
        self.del_t1_ipt.setObjectName("del_t1_ipt")
        self.gridLayout_8.addWidget(self.del_t1_ipt, 5, 2, 1, 1)
        self.del_t2_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_t2_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_t2_ipt.setDecimals(4)
        self.del_t2_ipt.setMinimum(0.0001)
        self.del_t2_ipt.setSingleStep(0.001)
        self.del_t2_ipt.setProperty("value", 0.02)
        self.del_t2_ipt.setObjectName("del_t2_ipt")
        self.gridLayout_8.addWidget(self.del_t2_ipt, 5, 3, 1, 1)
        self.del_x2_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_x2_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_x2_ipt.setDecimals(4)
        self.del_x2_ipt.setMinimum(0.0001)
        self.del_x2_ipt.setSingleStep(0.001)
        self.del_x2_ipt.setProperty("value", 0.01)
        self.del_x2_ipt.setObjectName("del_x2_ipt")
        self.gridLayout_8.addWidget(self.del_x2_ipt, 5, 9, 1, 1)
        self.del_alb2_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_alb2_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_alb2_ipt.setDecimals(4)
        self.del_alb2_ipt.setMinimum(0.0001)
        self.del_alb2_ipt.setSingleStep(0.001)
        self.del_alb2_ipt.setProperty("value", 0.05)
        self.del_alb2_ipt.setObjectName("del_alb2_ipt")
        self.gridLayout_8.addWidget(self.del_alb2_ipt, 5, 5, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.tab_12)
        self.label_64.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_64.setObjectName("label_64")
        self.gridLayout_8.addWidget(self.label_64, 4, 0, 1, 1)
        self.del_s1tmpf_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_s1tmpf_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_s1tmpf_ipt.setDecimals(4)
        self.del_s1tmpf_ipt.setMinimum(0.0001)
        self.del_s1tmpf_ipt.setSingleStep(0.001)
        self.del_s1tmpf_ipt.setProperty("value", 0.02)
        self.del_s1tmpf_ipt.setObjectName("del_s1tmpf_ipt")
        self.gridLayout_8.addWidget(self.del_s1tmpf_ipt, 7, 3, 1, 1)
        self.del_s2lng_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_s2lng_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_s2lng_ipt.setDecimals(4)
        self.del_s2lng_ipt.setMinimum(0.0001)
        self.del_s2lng_ipt.setSingleStep(0.001)
        self.del_s2lng_ipt.setProperty("value", 0.001)
        self.del_s2lng_ipt.setObjectName("del_s2lng_ipt")
        self.gridLayout_8.addWidget(self.del_s2lng_ipt, 7, 5, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_12)
        self.label_65.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_65.setObjectName("label_65")
        self.gridLayout_8.addWidget(self.label_65, 2, 4, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.tab_12)
        self.label_66.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_66.setObjectName("label_66")
        self.gridLayout_8.addWidget(self.label_66, 4, 9, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.tab_12)
        self.label_67.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_67.setObjectName("label_67")
        self.gridLayout_8.addWidget(self.label_67, 2, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.tab_12)
        self.label_68.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_68.setObjectName("label_68")
        self.gridLayout_8.addWidget(self.label_68, 4, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.tab_12)
        self.label_69.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_69.setObjectName("label_69")
        self.gridLayout_8.addWidget(self.label_69, 2, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.tab_12)
        self.label_70.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_70.setObjectName("label_70")
        self.gridLayout_8.addWidget(self.label_70, 2, 5, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.tab_12)
        self.label_71.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_71.setObjectName("label_71")
        self.gridLayout_8.addWidget(self.label_71, 2, 7, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.tab_12)
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_72.setStatusTip("")
        self.label_72.setObjectName("label_72")
        self.gridLayout_8.addWidget(self.label_72, 6, 5, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.tab_12)
        self.label_74.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_74.setStatusTip("")
        self.label_74.setObjectName("label_74")
        self.gridLayout_8.addWidget(self.label_74, 6, 4, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.tab_12)
        self.label_73.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_73.setObjectName("label_73")
        self.gridLayout_8.addWidget(self.label_73, 2, 3, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.tab_12)
        self.label_75.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_75.setObjectName("label_75")
        self.gridLayout_8.addWidget(self.label_75, 2, 8, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.tab_12)
        self.label_76.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_76.setStatusTip("")
        self.label_76.setWhatsThis("")
        self.label_76.setObjectName("label_76")
        self.gridLayout_8.addWidget(self.label_76, 6, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.tab_12)
        self.label_77.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_77.setObjectName("label_77")
        self.gridLayout_8.addWidget(self.label_77, 2, 9, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.tab_12)
        self.label_78.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_78.setObjectName("label_78")
        self.gridLayout_8.addWidget(self.label_78, 4, 3, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.tab_12)
        self.label_83.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_83.setObjectName("label_83")
        self.gridLayout_8.addWidget(self.label_83, 6, 2, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.tab_12)
        self.label_84.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_84.setObjectName("label_84")
        self.gridLayout_8.addWidget(self.label_84, 2, 6, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.tab_12)
        self.label_85.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_85.setObjectName("label_85")
        self.gridLayout_8.addWidget(self.label_85, 4, 2, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.tab_12)
        self.label_86.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_86.setObjectName("label_86")
        self.gridLayout_8.addWidget(self.label_86, 2, 2, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.tab_12)
        self.label_87.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_87.setStatusTip("")
        self.label_87.setObjectName("label_87")
        self.gridLayout_8.addWidget(self.label_87, 6, 7, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.tab_12)
        self.label_88.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_88.setObjectName("label_88")
        self.gridLayout_8.addWidget(self.label_88, 4, 4, 1, 1)
        self.del_a_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_a_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_a_ipt.setDecimals(4)
        self.del_a_ipt.setMinimum(0.0001)
        self.del_a_ipt.setSingleStep(0.001)
        self.del_a_ipt.setProperty("value", 0.05)
        self.del_a_ipt.setObjectName("del_a_ipt")
        self.gridLayout_8.addWidget(self.del_a_ipt, 3, 0, 1, 1)
        self.del_s1lng_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_s1lng_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_s1lng_ipt.setDecimals(4)
        self.del_s1lng_ipt.setMinimum(0.0001)
        self.del_s1lng_ipt.setSingleStep(0.001)
        self.del_s1lng_ipt.setProperty("value", 0.02)
        self.del_s1lng_ipt.setObjectName("del_s1lng_ipt")
        self.gridLayout_8.addWidget(self.del_s1lng_ipt, 7, 1, 1, 1)
        self.del_e_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_e_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_e_ipt.setDecimals(4)
        self.del_e_ipt.setMinimum(0.0001)
        self.del_e_ipt.setSingleStep(0.001)
        self.del_e_ipt.setProperty("value", 0.001)
        self.del_e_ipt.setObjectName("del_e_ipt")
        self.gridLayout_8.addWidget(self.del_e_ipt, 3, 1, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.tab_12)
        self.label_89.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_89.setObjectName("label_89")
        self.gridLayout_8.addWidget(self.label_89, 4, 8, 1, 1)
        self.setdeldefaults_btn = QtWidgets.QPushButton(self.tab_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setdeldefaults_btn.sizePolicy().hasHeightForWidth())
        self.setdeldefaults_btn.setSizePolicy(sizePolicy)
        self.setdeldefaults_btn.setObjectName("setdeldefaults_btn")
        self.gridLayout_8.addWidget(self.setdeldefaults_btn, 6, 8, 2, 2)
        self.label_90 = QtWidgets.QLabel(self.tab_12)
        self.label_90.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_90.setObjectName("label_90")
        self.gridLayout_8.addWidget(self.label_90, 6, 3, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.tab_12)
        self.label_91.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_91.setObjectName("label_91")
        self.gridLayout_8.addWidget(self.label_91, 6, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.tab_12)
        self.label_92.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_92.setObjectName("label_92")
        self.gridLayout_8.addWidget(self.label_92, 4, 6, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.tab_12)
        self.label_93.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_93.setStatusTip("")
        self.label_93.setObjectName("label_93")
        self.gridLayout_8.addWidget(self.label_93, 6, 6, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.tab_12)
        self.label_94.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_94.setObjectName("label_94")
        self.gridLayout_8.addWidget(self.label_94, 4, 5, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.tab_12)
        self.label_95.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_95.setObjectName("label_95")
        self.gridLayout_8.addWidget(self.label_95, 4, 7, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.tab_12)
        self.label_96.setObjectName("label_96")
        self.gridLayout_8.addWidget(self.label_96, 0, 0, 1, 10)
        self.line_14 = QtWidgets.QFrame(self.tab_12)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_8.addWidget(self.line_14, 1, 0, 1, 10)
        self.del_i_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_i_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_i_ipt.setDecimals(4)
        self.del_i_ipt.setMinimum(0.0001)
        self.del_i_ipt.setSingleStep(0.001)
        self.del_i_ipt.setProperty("value", 0.2)
        self.del_i_ipt.setObjectName("del_i_ipt")
        self.gridLayout_8.addWidget(self.del_i_ipt, 3, 2, 1, 1)
        self.del_q_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_q_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_q_ipt.setDecimals(4)
        self.del_q_ipt.setMinimum(0.0001)
        self.del_q_ipt.setSingleStep(0.001)
        self.del_q_ipt.setProperty("value", 0.003)
        self.del_q_ipt.setObjectName("del_q_ipt")
        self.gridLayout_8.addWidget(self.del_q_ipt, 3, 3, 1, 1)
        self.del_pshift_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_pshift_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_pshift_ipt.setDecimals(4)
        self.del_pshift_ipt.setMinimum(0.0001)
        self.del_pshift_ipt.setSingleStep(0.001)
        self.del_pshift_ipt.setProperty("value", 0.002)
        self.del_pshift_ipt.setObjectName("del_pshift_ipt")
        self.gridLayout_8.addWidget(self.del_pshift_ipt, 3, 4, 1, 1)
        self.del_s1agrad_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_s1agrad_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_s1agrad_ipt.setDecimals(4)
        self.del_s1agrad_ipt.setMinimum(0.0001)
        self.del_s1agrad_ipt.setSingleStep(0.001)
        self.del_s1agrad_ipt.setProperty("value", 0.001)
        self.del_s1agrad_ipt.setObjectName("del_s1agrad_ipt")
        self.gridLayout_8.addWidget(self.del_s1agrad_ipt, 7, 2, 1, 1)
        self.del_perr0_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_perr0_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_perr0_ipt.setDecimals(4)
        self.del_perr0_ipt.setMinimum(0.0001)
        self.del_perr0_ipt.setSingleStep(0.001)
        self.del_perr0_ipt.setProperty("value", 0.01)
        self.del_perr0_ipt.setObjectName("del_perr0_ipt")
        self.gridLayout_8.addWidget(self.del_perr0_ipt, 3, 5, 1, 1)
        self.del_pot1_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_pot1_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_pot1_ipt.setDecimals(4)
        self.del_pot1_ipt.setMinimum(0.0001)
        self.del_pot1_ipt.setSingleStep(0.001)
        self.del_pot1_ipt.setProperty("value", 0.02)
        self.del_pot1_ipt.setObjectName("del_pot1_ipt")
        self.gridLayout_8.addWidget(self.del_pot1_ipt, 3, 6, 1, 1)
        self.del_pot2_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_pot2_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_pot2_ipt.setDecimals(4)
        self.del_pot2_ipt.setMinimum(0.0001)
        self.del_pot2_ipt.setSingleStep(0.001)
        self.del_pot2_ipt.setProperty("value", 0.02)
        self.del_pot2_ipt.setObjectName("del_pot2_ipt")
        self.gridLayout_8.addWidget(self.del_pot2_ipt, 3, 7, 1, 1)
        self.del_l1_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_l1_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_l1_ipt.setDecimals(4)
        self.del_l1_ipt.setMinimum(0.0001)
        self.del_l1_ipt.setSingleStep(0.001)
        self.del_l1_ipt.setProperty("value", 0.01)
        self.del_l1_ipt.setObjectName("del_l1_ipt")
        self.gridLayout_8.addWidget(self.del_l1_ipt, 3, 8, 1, 1)
        self.del_l2_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_l2_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_l2_ipt.setDecimals(4)
        self.del_l2_ipt.setMinimum(0.0001)
        self.del_l2_ipt.setSingleStep(0.001)
        self.del_l2_ipt.setProperty("value", 0.01)
        self.del_l2_ipt.setObjectName("del_l2_ipt")
        self.gridLayout_8.addWidget(self.del_l2_ipt, 3, 9, 1, 1)
        self.del_s2lat_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_s2lat_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_s2lat_ipt.setDecimals(4)
        self.del_s2lat_ipt.setMinimum(0.0001)
        self.del_s2lat_ipt.setSingleStep(0.001)
        self.del_s2lat_ipt.setProperty("value", 0.02)
        self.del_s2lat_ipt.setObjectName("del_s2lat_ipt")
        self.gridLayout_8.addWidget(self.del_s2lat_ipt, 7, 4, 1, 1)
        self.del_f1_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_f1_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_f1_ipt.setDecimals(4)
        self.del_f1_ipt.setMinimum(0.0001)
        self.del_f1_ipt.setSingleStep(0.001)
        self.del_f1_ipt.setProperty("value", 0.01)
        self.del_f1_ipt.setObjectName("del_f1_ipt")
        self.gridLayout_8.addWidget(self.del_f1_ipt, 5, 6, 1, 1)
        self.del_s1lat_ipt = QtWidgets.QDoubleSpinBox(self.tab_12)
        self.del_s1lat_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.del_s1lat_ipt.setDecimals(4)
        self.del_s1lat_ipt.setMinimum(0.0001)
        self.del_s1lat_ipt.setSingleStep(0.001)
        self.del_s1lat_ipt.setProperty("value", 0.02)
        self.del_s1lat_ipt.setObjectName("del_s1lat_ipt")
        self.gridLayout_8.addWidget(self.del_s1lat_ipt, 7, 0, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_8)
        self.keepdel_tab_widget.addTab(self.tab_12, "")
        self.gridLayout_2.addWidget(self.keepdel_tab_widget, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.plot_btn = QtWidgets.QPushButton(self.tab)
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout_10.addWidget(self.plot_btn, 3, 0, 1, 5)
        self.data_combobox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_combobox.sizePolicy().hasHeightForWidth())
        self.data_combobox.setSizePolicy(sizePolicy)
        self.data_combobox.setObjectName("data_combobox")
        self.gridLayout_10.addWidget(self.data_combobox, 1, 0, 2, 3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.forcephase_chk = QtWidgets.QCheckBox(self.tab)
        self.forcephase_chk.setChecked(True)
        self.forcephase_chk.setObjectName("forcephase_chk")
        self.horizontalLayout_12.addWidget(self.forcephase_chk)
        self.uselc_chk = QtWidgets.QCheckBox(self.tab)
        self.uselc_chk.setEnabled(True)
        self.uselc_chk.setChecked(False)
        self.uselc_chk.setObjectName("uselc_chk")
        self.horizontalLayout_12.addWidget(self.uselc_chk)
        self.autoupdate_chk = QtWidgets.QCheckBox(self.tab)
        self.autoupdate_chk.setChecked(True)
        self.autoupdate_chk.setObjectName("autoupdate_chk")
        self.horizontalLayout_12.addWidget(self.autoupdate_chk)
        self.gridLayout_10.addLayout(self.horizontalLayout_12, 1, 4, 2, 1)
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_10.addWidget(self.line_8, 1, 3, 2, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_10)
        self.line_16 = QtWidgets.QFrame(self.tab)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_7.addWidget(self.line_16)
        self.plotwidget = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotwidget.sizePolicy().hasHeightForWidth())
        self.plotwidget.setSizePolicy(sizePolicy)
        self.plotwidget.setObjectName("plotwidget")
        self.verticalLayout_7.addWidget(self.plotwidget)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 2, 3, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 1)
        self.result_tab_widget = QtWidgets.QTabWidget(self.tab)
        self.result_tab_widget.setMaximumSize(QtCore.QSize(825, 16777215))
        self.result_tab_widget.setObjectName("result_tab_widget")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.component_treewidget = QtWidgets.QTreeWidget(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.component_treewidget.sizePolicy().hasHeightForWidth())
        self.component_treewidget.setSizePolicy(sizePolicy)
        self.component_treewidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.component_treewidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.component_treewidget.setAlternatingRowColors(True)
        self.component_treewidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.component_treewidget.setObjectName("component_treewidget")
        self.gridLayout_6.addWidget(self.component_treewidget, 0, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.tab_9)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_6.addWidget(self.line_11, 1, 0, 1, 4)
        self.result_treewidget = QtWidgets.QTreeWidget(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_treewidget.sizePolicy().hasHeightForWidth())
        self.result_treewidget.setSizePolicy(sizePolicy)
        self.result_treewidget.setAlternatingRowColors(True)
        self.result_treewidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.result_treewidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.result_treewidget.setHeaderHidden(False)
        self.result_treewidget.setObjectName("result_treewidget")
        self.gridLayout_6.addWidget(self.result_treewidget, 0, 0, 1, 1)
        self.residual_treewidget = QtWidgets.QTreeWidget(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.residual_treewidget.sizePolicy().hasHeightForWidth())
        self.residual_treewidget.setSizePolicy(sizePolicy)
        self.residual_treewidget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.residual_treewidget.setAlternatingRowColors(True)
        self.residual_treewidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.residual_treewidget.setObjectName("residual_treewidget")
        self.gridLayout_6.addWidget(self.residual_treewidget, 2, 0, 1, 4)
        self.line_10 = QtWidgets.QFrame(self.tab_9)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_6.addWidget(self.line_10, 0, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.tab_9)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_6.addWidget(self.line_7, 0, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_6)
        self.result_tab_widget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.curvestat_treewidget = QtWidgets.QTreeWidget(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curvestat_treewidget.sizePolicy().hasHeightForWidth())
        self.curvestat_treewidget.setSizePolicy(sizePolicy)
        self.curvestat_treewidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.curvestat_treewidget.setIndentation(0)
        self.curvestat_treewidget.setColumnCount(5)
        self.curvestat_treewidget.setObjectName("curvestat_treewidget")
        self.verticalLayout_5.addWidget(self.curvestat_treewidget)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.result_tab_widget.addTab(self.tab_10, "")
        self.tab_111 = QtWidgets.QWidget()
        self.tab_111.setObjectName("tab_111")
        self.horizontalLayout_91 = QtWidgets.QHBoxLayout(self.tab_111)
        self.horizontalLayout_91.setObjectName("horizontalLayout_91")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.phys_params_treewidget = QtWidgets.QTreeWidget(self.tab_111)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phys_params_treewidget.sizePolicy().hasHeightForWidth())
        self.phys_params_treewidget.setSizePolicy(sizePolicy)
        self.phys_params_treewidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.phys_params_treewidget.setIndentation(0)
        self.phys_params_treewidget.setColumnCount(6)
        self.phys_params_treewidget.setObjectName("phys_params_treewidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.phys_params_treewidget)
        self.verticalLayout_51.addWidget(self.phys_params_treewidget)
        self.horizontalLayout_91.addLayout(self.verticalLayout_51)
        self.result_tab_widget.addTab(self.tab_111, "")
        self.gridLayout_2.addWidget(self.result_tab_widget, 2, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 0, 1, 3, 1)
        self.tab_widget.addTab(self.tab, "")
        self.verticalLayout_9.addWidget(self.tab_widget)

        self.retranslateUi(DCWidget)
        self.tab_widget.setCurrentIndex(0)
        self.keepdel_tab_widget.setCurrentIndex(0)
        self.result_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DCWidget)

    def retranslateUi(self, DCWidget):
        _translate = QtCore.QCoreApplication.translate
        DCWidget.setWindowTitle(_translate("DCWidget", "Run Differential Corrections"))
        self.exportresults_btn.setText(_translate("DCWidget", "Export Results"))
        self.viewlastdcin_btn.setText(_translate("DCWidget", "dcin.active"))
        self.label.setToolTip(_translate("DCWidget", "Itertations performed by PyWD. After each iteration, results will be copied into inputs."))
        self.label.setText(_translate("DCWidget", "External Iterations"))
        self.label_8.setToolTip(_translate("DCWidget", "Iterations performed by Wilson - Devinney [NITER]"))
        self.label_8.setText(_translate("DCWidget", "Internal Iterations"))
        self.updateinputs_btn.setText(_translate("DCWidget", "Update Inputs"))
        self.viewlaastdcout_btn.setText(_translate("DCWidget", "dcout.active"))
        self.removesubset_btn.setText(_translate("DCWidget", "Remove Subset"))
        self.addsubset_btn.setText(_translate("DCWidget", "Add Subset"))
        self.rundc2015_btn.setText(_translate("DCWidget", "Run DC"))
        self.logd_chk.setText(_translate("DCWidget", "log(d)"))
        self.s2long_chk.setText(_translate("DCWidget", "S2 Lon"))
        self.t2_chk.setText(_translate("DCWidget", "T2"))
        self.f2_chk.setText(_translate("DCWidget", "F2"))
        self.el3_chk.setText(_translate("DCWidget", "L3"))
        self.s1tmax1_chk.setText(_translate("DCWidget", "S1 Tmax1"))
        self.s1lat_chk.setText(_translate("DCWidget", "S1 Lat."))
        self.s2temp_chk.setText(_translate("DCWidget", "S2 Temp."))
        self.g2_chk.setText(_translate("DCWidget", "g2"))
        self.p0_chk.setText(_translate("DCWidget", "P"))
        self.s1tstart_chk.setText(_translate("DCWidget", "S1 Tstart"))
        self.pot1_chk.setText(_translate("DCWidget", "Ω 1"))
        self.s1rad_chk.setText(_translate("DCWidget", "S1 Rad."))
        self.x1_chk.setText(_translate("DCWidget", "x1"))
        self.p3b_chk.setText(_translate("DCWidget", "P (3B)"))
        self.s2tmax1_chk.setText(_translate("DCWidget", "S2 Tmax1"))
        self.dpdt_chk.setText(_translate("DCWidget", "dP/dt"))
        self.t1_chk.setText(_translate("DCWidget", "T1"))
        self.q_chk.setText(_translate("DCWidget", "q (M2/M1)"))
        self.jd0_chk.setText(_translate("DCWidget", "T0"))
        self.s2tstart_chk.setText(_translate("DCWidget", "S2 Tstart"))
        self.l1_chk.setText(_translate("DCWidget", "L1"))
        self.perr0_chk.setText(_translate("DCWidget", "ω"))
        self.incl_chk.setText(_translate("DCWidget", "i"))
        self.s1long_chk.setText(_translate("DCWidget", "S1 Lon."))
        self.f1_chk.setText(_translate("DCWidget", "F1"))
        self.s2tmax2_chk.setText(_translate("DCWidget", "S2 Tmax2"))
        self.s1tmax2_chk.setText(_translate("DCWidget", "S1 Tmax2"))
        self.l2_chk.setText(_translate("DCWidget", "L2"))
        self.e3b_chk.setText(_translate("DCWidget", "e (3B)"))
        self.alb1_chk.setText(_translate("DCWidget", "A1"))
        self.xinc3b_chk.setText(_translate("DCWidget", "i (3B)"))
        self.pshift_chk.setText(_translate("DCWidget", "PShift"))
        self.x2_chk.setText(_translate("DCWidget", "x2"))
        self.desextinc_chk.setToolTip(_translate("DCWidget", "DESEXTINC"))
        self.desextinc_chk.setText(_translate("DCWidget", "Des. Ex."))
        self.a3b_chk.setText(_translate("DCWidget", "a (3B)"))
        self.tc3b_chk.setText(_translate("DCWidget", "T0 (3B)"))
        self.perr3b_chk.setText(_translate("DCWidget", " ω (3B)"))
        self.vgam_chk.setText(_translate("DCWidget", "Vγ"))
        self.s2rad_chk.setText(_translate("DCWidget", "S2 Rad."))
        self.s1tend_chk.setText(_translate("DCWidget", "S1 Tend"))
        self.g1_chk.setText(_translate("DCWidget", "g1"))
        self.dperdt_chk.setText(_translate("DCWidget", "dω/dt"))
        self.s2tend_chk.setText(_translate("DCWidget", "S2 Tend"))
        self.pot2_chk.setText(_translate("DCWidget", "Ω 2"))
        self.alb2_chk.setText(_translate("DCWidget", "A2"))
        self.e_chk.setText(_translate("DCWidget", "e"))
        self.s1temp_chk.setText(_translate("DCWidget", "S1 Temp."))
        self.s2lat_chk.setText(_translate("DCWidget", "S2 Lat."))
        self.a_chk.setText(_translate("DCWidget", "a"))
        self.label_2.setText(_translate("DCWidget", "Select parameters for adjustment with differential correction."))
        self.clearbaseset_btn.setText(_translate("DCWidget", "Clear"))
        self.label_3.setToolTip(_translate("DCWidget", "XLAMDA"))
        self.label_3.setText(_translate("DCWidget", "Marquardt λ (Damping):"))
        self.label_81.setToolTip(_translate("DCWidget", "The fraction of DC’s output corrections to be applied to the input parameters to form the output parameters."))
        self.label_81.setStatusTip(_translate("DCWidget", "VLR"))
        self.label_81.setText(_translate("DCWidget", "Vector Lenght Reduction:"))
        self.keepdel_tab_widget.setTabText(self.keepdel_tab_widget.indexOf(self.tab_11), _translate("DCWidget", "KEEP\'s"))
        self.label_64.setToolTip(_translate("DCWidget", "Gravity darkening exponent"))
        self.label_64.setText(_translate("DCWidget", "g1"))
        self.label_65.setToolTip(_translate("DCWidget", "Phase Shift"))
        self.label_65.setText(_translate("DCWidget", "Pshift"))
        self.label_66.setToolTip(_translate("DCWidget", "Limb darkening coefficient"))
        self.label_66.setText(_translate("DCWidget", "x2"))
        self.label_67.setToolTip(_translate("DCWidget", "Semi-major axis"))
        self.label_67.setText(_translate("DCWidget", "a"))
        self.label_68.setToolTip(_translate("DCWidget", "Gravity darkening exponent"))
        self.label_68.setText(_translate("DCWidget", "g2"))
        self.label_69.setToolTip(_translate("DCWidget", "<html><head/><body><p>Orbital eccentricity</p></body></html>"))
        self.label_69.setText(_translate("DCWidget", "e"))
        self.label_70.setToolTip(_translate("DCWidget", "<html><head/><body><p>Argument of periastron</p></body></html>"))
        self.label_70.setText(_translate("DCWidget", "ω"))
        self.label_71.setToolTip(_translate("DCWidget", "Surface potential"))
        self.label_71.setText(_translate("DCWidget", "Ω 2"))
        self.label_72.setToolTip(_translate("DCWidget", "Spot 2 Longitude"))
        self.label_72.setText(_translate("DCWidget", "S2 LON"))
        self.label_74.setToolTip(_translate("DCWidget", "Spot 2 Latitude"))
        self.label_74.setText(_translate("DCWidget", "S2 LAT"))
        self.label_73.setToolTip(_translate("DCWidget", "Mass ratio, star 2/star 1"))
        self.label_73.setText(_translate("DCWidget", "q (M2/M1)"))
        self.label_75.setToolTip(_translate("DCWidget", "Relative monochromatic luminosity"))
        self.label_75.setText(_translate("DCWidget", "L1"))
        self.label_76.setToolTip(_translate("DCWidget", "Spot 1 Latitude"))
        self.label_76.setText(_translate("DCWidget", "S1 LAT"))
        self.label_77.setToolTip(_translate("DCWidget", "Relative monochromatic luminosity"))
        self.label_77.setText(_translate("DCWidget", "L2"))
        self.label_78.setToolTip(_translate("DCWidget", "Average surface temperature in 10000K"))
        self.label_78.setText(_translate("DCWidget", "T2"))
        self.label_83.setToolTip(_translate("DCWidget", "Spot 1 Angular Radius"))
        self.label_83.setText(_translate("DCWidget", "S1 RAD"))
        self.label_84.setToolTip(_translate("DCWidget", "Surface potential"))
        self.label_84.setText(_translate("DCWidget", "Ω 1"))
        self.label_85.setToolTip(_translate("DCWidget", "Average surface temperature in 10000K"))
        self.label_85.setText(_translate("DCWidget", "T1"))
        self.label_86.setToolTip(_translate("DCWidget", "Inclination"))
        self.label_86.setText(_translate("DCWidget", "i"))
        self.label_87.setToolTip(_translate("DCWidget", "Spot 2 Temperature Factor"))
        self.label_87.setText(_translate("DCWidget", "S2 TEMP"))
        self.label_88.setToolTip(_translate("DCWidget", "Bolometric Albedo"))
        self.label_88.setText(_translate("DCWidget", "ALB1"))
        self.label_89.setToolTip(_translate("DCWidget", "Limb darkening coefficient"))
        self.label_89.setText(_translate("DCWidget", "x1"))
        self.setdeldefaults_btn.setText(_translate("DCWidget", "Set Defaults"))
        self.label_90.setToolTip(_translate("DCWidget", "Spot 1 Temperature Factor"))
        self.label_90.setText(_translate("DCWidget", "S1 TEMP"))
        self.label_91.setToolTip(_translate("DCWidget", "Spot 1 Longitude"))
        self.label_91.setText(_translate("DCWidget", "S1 LON"))
        self.label_92.setToolTip(_translate("DCWidget", "Ratio of axial rotation rate vs. mean orbital rate"))
        self.label_92.setText(_translate("DCWidget", "F1"))
        self.label_93.setToolTip(_translate("DCWidget", "Spot 2 Angular Radius"))
        self.label_93.setText(_translate("DCWidget", "S2 RAD"))
        self.label_94.setToolTip(_translate("DCWidget", "Bolometric Albedo"))
        self.label_94.setText(_translate("DCWidget", "ALB2"))
        self.label_95.setToolTip(_translate("DCWidget", "Ratio of axial rotation rate vs. mean orbital rate"))
        self.label_95.setText(_translate("DCWidget", "F2"))
        self.label_96.setText(_translate("DCWidget", "Parameter increments for approximating derivatives in finite differences. "))
        self.keepdel_tab_widget.setTabText(self.keepdel_tab_widget.indexOf(self.tab_12), _translate("DCWidget", "DEL\'s"))
        self.plot_btn.setText(_translate("DCWidget", "Plot"))
        self.forcephase_chk.setToolTip(_translate("DCWidget", "<html><head/><body><p>If checked and input is in HJD, observations and model will be converted into phases (in 0 - 1 range) before plotting.</p><p>Nothing will be done if already working in phases. </p></body></html>"))
        self.forcephase_chk.setText(_translate("DCWidget", "Force Phase"))
        self.uselc_chk.setToolTip(_translate("DCWidget", "Use LC to output higher resolution model curve. [?]"))
        self.uselc_chk.setWhatsThis(_translate("DCWidget", "This will generate a lcin.active file and run LC, then plot synthetic results onto the observations, instead of reading from dcout.active file. UI will freeze for a moment to compute synthetic points.\n"
"\n"
"Line plotting will be used for LC synthetic points. DC outputs will be plotted with scatter plot."))
        self.uselc_chk.setText(_translate("DCWidget", "Use LC"))
        self.autoupdate_chk.setToolTip(_translate("DCWidget", "Plot automatically after each iteration."))
        self.autoupdate_chk.setText(_translate("DCWidget", "Auto Update"))
        self.component_treewidget.headerItem().setText(0, _translate("DCWidget", "Component"))
        self.component_treewidget.headerItem().setText(1, _translate("DCWidget", "r (R/a)"))
        self.component_treewidget.headerItem().setText(2, _translate("DCWidget", "Std. Err."))
        self.result_treewidget.headerItem().setText(0, _translate("DCWidget", "Parameter"))
        self.result_treewidget.headerItem().setText(1, _translate("DCWidget", "Input"))
        self.result_treewidget.headerItem().setText(2, _translate("DCWidget", "Adjustment"))
        self.result_treewidget.headerItem().setText(3, _translate("DCWidget", "Output"))
        self.result_treewidget.headerItem().setText(4, _translate("DCWidget", "Standard Error"))
        self.residual_treewidget.headerItem().setText(0, _translate("DCWidget", "Mean Residual for Input Values"))
        self.residual_treewidget.headerItem().setText(1, _translate("DCWidget", "Mean Residual Predicted"))
        self.residual_treewidget.headerItem().setText(2, _translate("DCWidget", "Determinant"))
        self.residual_treewidget.headerItem().setText(3, _translate("DCWidget", "Run Time"))
        self.result_tab_widget.setTabText(self.result_tab_widget.indexOf(self.tab_9), _translate("DCWidget", "Results"))
        self.curvestat_treewidget.headerItem().setText(0, _translate("DCWidget", "Band"))
        self.curvestat_treewidget.headerItem().setText(1, _translate("DCWidget", "# of Observations"))
        self.curvestat_treewidget.headerItem().setStatusTip(1, _translate("DCWidget", "Number of observations."))
        self.curvestat_treewidget.headerItem().setToolTip(1, _translate("DCWidget", "Number of observations."))
        self.curvestat_treewidget.headerItem().setText(2, _translate("DCWidget", "Standard Deviation"))
        self.curvestat_treewidget.headerItem().setToolTip(2, _translate("DCWidget", "Standard deviation."))
        self.curvestat_treewidget.headerItem().setText(3, _translate("DCWidget", "# of Obs. in Phs. Rng."))
        self.curvestat_treewidget.headerItem().setToolTip(3, _translate("DCWidget", "Number of observations in phase range as configured in curve properties."))
        self.curvestat_treewidget.headerItem().setText(4, _translate("DCWidget", "Std. Dev. in Phs. Rng."))
        self.curvestat_treewidget.headerItem().setToolTip(4, _translate("DCWidget", "Standard deviation in phase range as configured in curve properties."))
        self.result_tab_widget.setTabText(self.result_tab_widget.indexOf(self.tab_10), _translate("DCWidget", "Statistical Curve Information"))
        self.phys_params_treewidget.headerItem().setText(0, _translate("DCWidget", "Abs. Parameters"))
        self.phys_params_treewidget.headerItem().setText(1, _translate("DCWidget", "Value"))
        self.phys_params_treewidget.headerItem().setText(2, _translate("DCWidget", "LC Info"))
        self.phys_params_treewidget.headerItem().setText(3, _translate("DCWidget", "Value"))
        self.phys_params_treewidget.headerItem().setText(4, _translate("DCWidget", "RV Info"))
        self.phys_params_treewidget.headerItem().setText(5, _translate("DCWidget", "Value"))
        __sortingEnabled = self.phys_params_treewidget.isSortingEnabled()
        self.phys_params_treewidget.setSortingEnabled(False)
        self.phys_params_treewidget.topLevelItem(0).setText(0, _translate("DCWidget", "a (R☉)"))
        self.phys_params_treewidget.topLevelItem(0).setText(2, _translate("DCWidget", "r1 (R1/a)"))
        self.phys_params_treewidget.topLevelItem(0).setText(4, _translate("DCWidget", "K1 (km/s)"))
        self.phys_params_treewidget.topLevelItem(1).setText(0, _translate("DCWidget", "M1 (M☉)"))
        self.phys_params_treewidget.topLevelItem(1).setText(2, _translate("DCWidget", "r2 (R2/a)"))
        self.phys_params_treewidget.topLevelItem(1).setText(4, _translate("DCWidget", "K2 (km/s)"))
        self.phys_params_treewidget.topLevelItem(2).setText(0, _translate("DCWidget", "M2 (M☉)"))
        self.phys_params_treewidget.topLevelItem(2).setText(2, _translate("DCWidget", "r1+r2"))
        self.phys_params_treewidget.topLevelItem(3).setText(0, _translate("DCWidget", "R1 (R☉)"))
        self.phys_params_treewidget.topLevelItem(3).setText(2, _translate("DCWidget", "k (r2/r1)"))
        self.phys_params_treewidget.topLevelItem(4).setText(0, _translate("DCWidget", "R2 (R☉)"))
        self.phys_params_treewidget.topLevelItem(4).setText(2, _translate("DCWidget", "x1"))
        self.phys_params_treewidget.topLevelItem(5).setText(0, _translate("DCWidget", "Teff1 (K)"))
        self.phys_params_treewidget.topLevelItem(5).setText(2, _translate("DCWidget", "x2"))
        self.phys_params_treewidget.topLevelItem(6).setText(0, _translate("DCWidget", "Teff2 (K)"))
        self.phys_params_treewidget.topLevelItem(6).setText(2, _translate("DCWidget", "y1"))
        self.phys_params_treewidget.topLevelItem(7).setText(0, _translate("DCWidget", "logg1 (cgs)"))
        self.phys_params_treewidget.topLevelItem(7).setText(2, _translate("DCWidget", "y2"))
        self.phys_params_treewidget.topLevelItem(8).setText(0, _translate("DCWidget", "logg2 (cgs)"))
        self.phys_params_treewidget.topLevelItem(8).setText(2, _translate("DCWidget", "L2/L1"))
        self.phys_params_treewidget.topLevelItem(9).setText(0, _translate("DCWidget", "Mbol1 (mag)"))
        self.phys_params_treewidget.topLevelItem(10).setText(0, _translate("DCWidget", "Mbol2 (mag)"))
        self.phys_params_treewidget.topLevelItem(11).setText(0, _translate("DCWidget", "log (L1/L☉)"))
        self.phys_params_treewidget.topLevelItem(12).setText(0, _translate("DCWidget", "log (L2/L☉)"))
        self.phys_params_treewidget.setSortingEnabled(__sortingEnabled)
        self.result_tab_widget.setTabText(self.result_tab_widget.indexOf(self.tab_111), _translate("DCWidget", "System Information"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("DCWidget", "Base Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DCWidget = QtWidgets.QWidget()
    ui = Ui_DCWidget()
    ui.setupUi(DCWidget)
    DCWidget.show()
    sys.exit(app.exec_())

