# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eclipsetimings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EclipseWidget(object):
    def setupUi(self, EclipseWidget):
        EclipseWidget.setObjectName("EclipseWidget")
        EclipseWidget.resize(375, 600)
        EclipseWidget.setMinimumSize(QtCore.QSize(375, 600))
        EclipseWidget.setMaximumSize(QtCore.QSize(400, 900))
        self.gridLayout = QtWidgets.QGridLayout(EclipseWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtWidgets.QLabel(EclipseWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.ksd_box = QtWidgets.QSpinBox(EclipseWidget)
        self.ksd_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.ksd_box.setMinimum(1)
        self.ksd_box.setMaximum(3)
        self.ksd_box.setProperty("value", 1)
        self.ksd_box.setObjectName("ksd_box")
        self.gridLayout.addWidget(self.ksd_box, 5, 1, 1, 1)
        self.datawidget = QtWidgets.QTreeWidget(EclipseWidget)
        self.datawidget.setObjectName("datawidget")
        self.gridLayout.addWidget(self.datawidget, 9, 0, 1, 5)
        self.label_11 = QtWidgets.QLabel(EclipseWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(EclipseWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 2)
        self.constant_weight_checkbox = QtWidgets.QCheckBox(EclipseWidget)
        self.constant_weight_checkbox.setObjectName("constant_weight_checkbox")
        self.gridLayout.addWidget(self.constant_weight_checkbox, 3, 0, 1, 5)
        self.filepath_label = QtWidgets.QLabel(EclipseWidget)
        self.filepath_label.setObjectName("filepath_label")
        self.gridLayout.addWidget(self.filepath_label, 8, 0, 1, 5)
        self.line_12 = QtWidgets.QFrame(EclipseWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 1, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(EclipseWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 5)
        self.line_13 = QtWidgets.QFrame(EclipseWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 6, 0, 1, 5)
        self.label_53 = QtWidgets.QLabel(EclipseWidget)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 0, 0, 1, 5)
        self.line = QtWidgets.QFrame(EclipseWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 2, 1, 1)
        self.iftime_chk = QtWidgets.QCheckBox(EclipseWidget)
        self.iftime_chk.setObjectName("iftime_chk")
        self.gridLayout.addWidget(self.iftime_chk, 2, 0, 1, 4)
        self.load_btn = QtWidgets.QPushButton(EclipseWidget)
        self.load_btn.setObjectName("load_btn")
        self.gridLayout.addWidget(self.load_btn, 10, 0, 1, 5)
        self.clear_btn = QtWidgets.QPushButton(EclipseWidget)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 11, 0, 1, 5)
        self.sigma_ipt = QtWidgets.QDoubleSpinBox(EclipseWidget)
        self.sigma_ipt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sigma_ipt.setDecimals(8)
        self.sigma_ipt.setMaximum(99999.0)
        self.sigma_ipt.setObjectName("sigma_ipt")
        self.gridLayout.addWidget(self.sigma_ipt, 5, 4, 1, 1)

        self.retranslateUi(EclipseWidget)
        QtCore.QMetaObject.connectSlotsByName(EclipseWidget)

    def retranslateUi(self, EclipseWidget):
        _translate = QtCore.QCoreApplication.translate
        EclipseWidget.setWindowTitle(_translate("EclipseWidget", "Eclipse Timings"))
        self.label_16.setToolTip(_translate("EclipseWidget", "Set standard deviation apply method. [?]"))
        self.label_16.setWhatsThis(_translate("EclipseWidget", "<html><head/><body><p>An integer array that is 0, 1, or 2 for each input sub-dataset (velocity, light, or eclipse timings). </p><p>The KSDs tell DC whether to apply the input standard deviations (σ’s) to compute curvedependent weights (KSD=0), </p><p>to apply DC’s internally computed σ’s for the weights (KSD=1),</p><p>or to apply σ’s based on one or two restricted phase ranges for the weights (KSD=2).</p><p><span style=\" font-weight:600;\">If unsure, set to 1.</span></p></body></html>"))
        self.label_16.setText(_translate("EclipseWidget", "KSD"))
        self.datawidget.headerItem().setText(0, _translate("EclipseWidget", "Time"))
        self.datawidget.headerItem().setText(1, _translate("EclipseWidget", "Eclipse Type"))
        self.datawidget.headerItem().setText(2, _translate("EclipseWidget", "Weight"))
        self.label_11.setToolTip(_translate("EclipseWidget", "Estimated standard deviation of observed light"))
        self.label_11.setText(_translate("EclipseWidget", "SIGMA"))
        self.label.setText(_translate("EclipseWidget", "Data preview of file:"))
        self.constant_weight_checkbox.setToolTip(_translate("EclipseWidget", "<html><head/><body><p>If checked, third column will be ignored and all weights will be assumed as unity.</p><p>If there isn\'t a third column, program will fill weights with unity too, regardless of this option.</p></body></html>"))
        self.constant_weight_checkbox.setText(_translate("EclipseWidget", "Use constant weights (1.0)"))
        self.filepath_label.setText(_translate("EclipseWidget", "None"))
        self.label_53.setText(_translate("EclipseWidget", "Load eclipse timings from a file"))
        self.iftime_chk.setText(_translate("EclipseWidget", "IFTIME - Write eclipse timings"))
        self.load_btn.setText(_translate("EclipseWidget", "Load"))
        self.clear_btn.setText(_translate("EclipseWidget", "Clear"))

