# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lcdcpicker_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LCDCPickerDialog(object):
    def setupUi(self, LCDCPickerDialog):
        LCDCPickerDialog.setObjectName("LCDCPickerDialog")
        LCDCPickerDialog.resize(700, 500)
        LCDCPickerDialog.setMinimumSize(QtCore.QSize(700, 500))
        LCDCPickerDialog.setMaximumSize(QtCore.QSize(700, 500))
        self.gridLayout_4 = QtWidgets.QGridLayout(LCDCPickerDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(LCDCPickerDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pickdc_btn = QtWidgets.QPushButton(self.groupBox)
        self.pickdc_btn.setObjectName("pickdc_btn")
        self.gridLayout_2.addWidget(self.pickdc_btn, 1, 3, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.groupBox)
        self.label_68.setObjectName("label_68")
        self.gridLayout_2.addWidget(self.label_68, 0, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.groupBox)
        self.label_67.setObjectName("label_67")
        self.gridLayout_2.addWidget(self.label_67, 1, 0, 1, 1)
        self.picklc_btn = QtWidgets.QPushButton(self.groupBox)
        self.picklc_btn.setObjectName("picklc_btn")
        self.gridLayout_2.addWidget(self.picklc_btn, 0, 3, 1, 1)
        self.dcpath_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcpath_label.sizePolicy().hasHeightForWidth())
        self.dcpath_label.setSizePolicy(sizePolicy)
        self.dcpath_label.setText("")
        self.dcpath_label.setObjectName("dcpath_label")
        self.gridLayout_2.addWidget(self.dcpath_label, 1, 2, 1, 1)
        self.lcpath_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcpath_label.sizePolicy().hasHeightForWidth())
        self.lcpath_label.setSizePolicy(sizePolicy)
        self.lcpath_label.setText("")
        self.lcpath_label.setObjectName("lcpath_label")
        self.gridLayout_2.addWidget(self.lcpath_label, 0, 1, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 3, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(LCDCPickerDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_65 = QtWidgets.QLabel(self.groupBox_2)
        self.label_65.setObjectName("label_65")
        self.gridLayout.addWidget(self.label_65, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.groupBox_2)
        self.label_66.setObjectName("label_66")
        self.gridLayout.addWidget(self.label_66, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.line = QtWidgets.QFrame(LCDCPickerDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(LCDCPickerDialog)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(LCDCPickerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_btn = QtWidgets.QPushButton(LCDCPickerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.exit_btn = QtWidgets.QPushButton(LCDCPickerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.gridLayout_4.addLayout(self.horizontalLayout, 6, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(LCDCPickerDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 5, 0, 1, 2)

        self.retranslateUi(LCDCPickerDialog)
        QtCore.QMetaObject.connectSlotsByName(LCDCPickerDialog)

    def retranslateUi(self, LCDCPickerDialog):
        _translate = QtCore.QCoreApplication.translate
        LCDCPickerDialog.setWindowTitle(_translate("LCDCPickerDialog", "PyWD2015"))
        self.groupBox.setTitle(_translate("LCDCPickerDialog", "Paths"))
        self.pickdc_btn.setText(_translate("LCDCPickerDialog", "Pick File"))
        self.label_68.setText(_translate("LCDCPickerDialog", "LC Binary:"))
        self.label_67.setText(_translate("LCDCPickerDialog", "DC Binary:"))
        self.picklc_btn.setText(_translate("LCDCPickerDialog", "Pick File"))
        self.groupBox_2.setTitle(_translate("LCDCPickerDialog", "Links"))
        self.label_65.setText(_translate("LCDCPickerDialog", "WD Homepage:"))
        self.lineEdit.setText(_translate("LCDCPickerDialog", "github.com/Varnani/PyWD2015"))
        self.label_66.setText(_translate("LCDCPickerDialog", "GitHub:"))
        self.lineEdit_2.setText(_translate("LCDCPickerDialog", "github.com/rewilsonufl/ebmodel"))
        self.label_2.setText(_translate("LCDCPickerDialog", "PyWD2015 is a GUI for 2015 version of LC and DC programs of Wilson - Devinney (WD) eclipsing binary modeling code. PyWD2015 needs these programs to function. Please provide their paths below.\n"
"\n"
"Precompiled WD binaries and associated limb darkening tables are hosted on GitHub release page with permissions of Dr. Robert E. Wilson and Dr. Walter Van Hamme. You can also obtain source codes and limb darkening tables from the WD Homepage and compile LC and DC codes yourself."))
        self.label.setText(_translate("LCDCPickerDialog", "Welcome to PyWD2015"))
        self.save_btn.setText(_translate("LCDCPickerDialog", "Save"))
        self.exit_btn.setText(_translate("LCDCPickerDialog", "Exit"))

