# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starpositions_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StarPositionWidget(object):
    def setupUi(self, StarPositionWidget):
        StarPositionWidget.setObjectName("StarPositionWidget")
        StarPositionWidget.resize(800, 600)
        StarPositionWidget.setMinimumSize(QtCore.QSize(800, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(StarPositionWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(StarPositionWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.positions_groupbox = QtWidgets.QGroupBox(self.tab_2)
        self.positions_groupbox.setCheckable(True)
        self.positions_groupbox.setObjectName("positions_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.positions_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.positions_groupbox)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.phase_spinbox = QtWidgets.QDoubleSpinBox(self.positions_groupbox)
        self.phase_spinbox.setEnabled(True)
        self.phase_spinbox.setMinimumSize(QtCore.QSize(70, 0))
        self.phase_spinbox.setDecimals(4)
        self.phase_spinbox.setMinimum(0.0)
        self.phase_spinbox.setMaximum(1.0)
        self.phase_spinbox.setSingleStep(0.01)
        self.phase_spinbox.setProperty("value", 0.25)
        self.phase_spinbox.setObjectName("phase_spinbox")
        self.gridLayout_2.addWidget(self.phase_spinbox, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.positions_groupbox, 0, 0, 1, 1)
        self.roche_groupbox = QtWidgets.QGroupBox(self.tab_2)
        self.roche_groupbox.setCheckable(True)
        self.roche_groupbox.setChecked(False)
        self.roche_groupbox.setObjectName("roche_groupbox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.roche_groupbox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.roche_groupbox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.inner_crit_otpt = QtWidgets.QDoubleSpinBox(self.roche_groupbox)
        self.inner_crit_otpt.setReadOnly(True)
        self.inner_crit_otpt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inner_crit_otpt.setDecimals(6)
        self.inner_crit_otpt.setMaximum(9999.0)
        self.inner_crit_otpt.setObjectName("inner_crit_otpt")
        self.gridLayout_4.addWidget(self.inner_crit_otpt, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.roche_groupbox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.outer_crit_otpt = QtWidgets.QDoubleSpinBox(self.roche_groupbox)
        self.outer_crit_otpt.setReadOnly(True)
        self.outer_crit_otpt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.outer_crit_otpt.setDecimals(6)
        self.outer_crit_otpt.setMaximum(9999.0)
        self.outer_crit_otpt.setObjectName("outer_crit_otpt")
        self.gridLayout_4.addWidget(self.outer_crit_otpt, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.roche_groupbox, 0, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_5.addWidget(self.line_6, 2, 0, 1, 2)
        self.plot_widget = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget.sizePolicy().hasHeightForWidth())
        self.plot_widget.setSizePolicy(sizePolicy)
        self.plot_widget.setObjectName("plot_widget")
        self.gridLayout_5.addWidget(self.plot_widget, 3, 0, 1, 2)
        self.plot_btn = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_btn.sizePolicy().hasHeightForWidth())
        self.plot_btn.setSizePolicy(sizePolicy)
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout_5.addWidget(self.plot_btn, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.saveframe_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.saveframe_btn.setEnabled(True)
        self.saveframe_btn.setObjectName("saveframe_btn")
        self.verticalLayout_2.addWidget(self.saveframe_btn)
        self.saveall_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.saveall_btn.setObjectName("saveall_btn")
        self.verticalLayout_2.addWidget(self.saveall_btn)
        self.gridLayout_3.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 1, 2, 1)
        self.viewport_pixlabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewport_pixlabel.sizePolicy().hasHeightForWidth())
        self.viewport_pixlabel.setSizePolicy(sizePolicy)
        self.viewport_pixlabel.setText("")
        self.viewport_pixlabel.setObjectName("viewport_pixlabel")
        self.gridLayout_3.addWidget(self.viewport_pixlabel, 0, 2, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.start_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.start_btn.setMaximumSize(QtCore.QSize(35, 35))
        self.start_btn.setText("")
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_2.addWidget(self.start_btn)
        self.pause_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.pause_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.pause_btn.setMaximumSize(QtCore.QSize(35, 35))
        self.pause_btn.setText("")
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout_2.addWidget(self.pause_btn)
        self.prev_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.prev_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_btn.sizePolicy().hasHeightForWidth())
        self.prev_btn.setSizePolicy(sizePolicy)
        self.prev_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.prev_btn.setMaximumSize(QtCore.QSize(35, 35))
        self.prev_btn.setText("")
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_2.addWidget(self.prev_btn)
        self.next_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.next_btn.setEnabled(True)
        self.next_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.next_btn.setMaximumSize(QtCore.QSize(35, 35))
        self.next_btn.setText("")
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_2.addWidget(self.next_btn)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(225, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(225, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.max_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.max_spinbox.setDecimals(1)
        self.max_spinbox.setMinimum(-100.0)
        self.max_spinbox.setMaximum(100.0)
        self.max_spinbox.setSingleStep(0.5)
        self.max_spinbox.setProperty("value", 1.5)
        self.max_spinbox.setObjectName("max_spinbox")
        self.gridLayout.addWidget(self.max_spinbox, 3, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.dpi_combobox = QtWidgets.QComboBox(self.groupBox)
        self.dpi_combobox.setObjectName("dpi_combobox")
        self.dpi_combobox.addItem("")
        self.dpi_combobox.addItem("")
        self.dpi_combobox.addItem("")
        self.dpi_combobox.addItem("")
        self.gridLayout.addWidget(self.dpi_combobox, 5, 1, 1, 3)
        self.render_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_btn.sizePolicy().hasHeightForWidth())
        self.render_btn.setSizePolicy(sizePolicy)
        self.render_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.render_btn.setObjectName("render_btn")
        self.gridLayout.addWidget(self.render_btn, 6, 0, 1, 4)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 4)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 4, 0, 1, 4)
        self.min_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.min_spinbox.setDecimals(1)
        self.min_spinbox.setMinimum(-100.0)
        self.min_spinbox.setMaximum(100.0)
        self.min_spinbox.setSingleStep(0.5)
        self.min_spinbox.setProperty("value", -1.5)
        self.min_spinbox.setObjectName("min_spinbox")
        self.gridLayout.addWidget(self.min_spinbox, 2, 2, 1, 2)
        self.single_chk = QtWidgets.QCheckBox(self.groupBox)
        self.single_chk.setObjectName("single_chk")
        self.gridLayout.addWidget(self.single_chk, 0, 0, 1, 1)
        self.render_phaseSpinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.render_phaseSpinbox.setEnabled(False)
        self.render_phaseSpinbox.setDecimals(2)
        self.render_phaseSpinbox.setMinimum(0.0)
        self.render_phaseSpinbox.setMaximum(1.0)
        self.render_phaseSpinbox.setSingleStep(0.01)
        self.render_phaseSpinbox.setProperty("value", 0.25)
        self.render_phaseSpinbox.setObjectName("render_phaseSpinbox")
        self.gridLayout.addWidget(self.render_phaseSpinbox, 0, 2, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message_label = QtWidgets.QLabel(self.tab)
        self.message_label.setMinimumSize(QtCore.QSize(150, 0))
        self.message_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.message_label.setObjectName("message_label")
        self.horizontalLayout.addWidget(self.message_label)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 4, 0, 1, 3)
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_3.addWidget(self.line_7, 3, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_3.addWidget(self.line_9, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(StarPositionWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StarPositionWidget)

    def retranslateUi(self, StarPositionWidget):
        _translate = QtCore.QCoreApplication.translate
        StarPositionWidget.setWindowTitle(_translate("StarPositionWidget", "Star Positions"))
        self.positions_groupbox.setTitle(_translate("StarPositionWidget", "Star Positions"))
        self.label_7.setText(_translate("StarPositionWidget", "Phase"))
        self.roche_groupbox.setTitle(_translate("StarPositionWidget", "Critical Roche Potentials"))
        self.label_12.setText(_translate("StarPositionWidget", "Inner Critical:"))
        self.label_9.setText(_translate("StarPositionWidget", "Outer Critical:"))
        self.plot_btn.setText(_translate("StarPositionWidget", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("StarPositionWidget", "Single Plot"))
        self.groupBox_3.setTitle(_translate("StarPositionWidget", "Output"))
        self.saveframe_btn.setText(_translate("StarPositionWidget", "Save Frame"))
        self.saveall_btn.setText(_translate("StarPositionWidget", "Save All"))
        self.groupBox_2.setTitle(_translate("StarPositionWidget", "Playback"))
        self.groupBox.setTitle(_translate("StarPositionWidget", "Render Settings"))
        self.label_4.setText(_translate("StarPositionWidget", "Axis Min"))
        self.label_5.setText(_translate("StarPositionWidget", "Axis Max"))
        self.label_8.setText(_translate("StarPositionWidget", "Resolution"))
        self.dpi_combobox.setItemText(0, _translate("StarPositionWidget", "64dpi"))
        self.dpi_combobox.setItemText(1, _translate("StarPositionWidget", "128dpi"))
        self.dpi_combobox.setItemText(2, _translate("StarPositionWidget", "196dpi"))
        self.dpi_combobox.setItemText(3, _translate("StarPositionWidget", "256dpi"))
        self.render_btn.setText(_translate("StarPositionWidget", "Render"))
        self.single_chk.setText(_translate("StarPositionWidget", "Single Phase"))
        self.message_label.setText(_translate("StarPositionWidget", "Ready"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("StarPositionWidget", "Animation"))

